### PR TITLE
Handle sessions stored from pre-v2.2 (warn and discard); closes https://github.com/nlf/connect-mysql/issues/47

### PR DESCRIPTION
**Pull request by danielsharvey**
Catch JSON parse exception, log warning including content, and discard (treat as session not found / new session).

### CODE REVIEW

**Comment by danielsharvey** [comment]
Not sure how you viewing warning messages - it may be enough to document lack of backward compatibility and silently discard old session data.

**Comment by jas-** [comment]
This landed in ‘v2.2.2’, thanks!

**Comment by danielsharvey** [comment]
Hi @jas-, I think there was a minor (merge) problem with `v2.2.3` - check out the NPM package

`https://registry.npmjs.org/connect-mysql/-/connect-mysql-2.2.3.tgz`

and the file `node_modules/connect-mysql/lib/connect-mysql.js` line ~46:

```
/**
 * Wrapper to extract digest, verify digest & decrypt cipher text
 */
function decryptData(ciphertext, secret, algorithm, hashing, encodeas) {
<<<<<<< HEAD
  if (ciphertext)
    ciphertext = JSON.parse(ciphertext);
=======
  if (ciphertext) {
    try {
      ciphertext = JSON.parse(ciphertext);
    } catch(e) {
      console.warn('WARNING: Discarding bad (possibly mysql-connect pre-v2.2) session data', ciphertext);
      return null;
    }
  }
>>>>>>> a804c7841bebef94e542d0d8e80d9d67c229d27e
```

Oops :(

**Comment by jas-** [comment]
Shoot, thanks for catching this! I need to talk to @nlf about this repository as every PR pulls in old, like 2 year old commits for some reason. I think its because I have a forked copy of this repo (due to permissions when I took over the package) that is used to create PR's from.

**Pull request merged**
